version: "3.3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"